# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

<hr>   
<center><b><h1>Vatsal Parmar | 23010101196</b></center>

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [ ]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [19]:
# static 
arr1 = np.array([1, 2, 3])
print(arr1)   

# zero to n-1
arr2 = np.arange(5)
print(arr2)

# start to last-1
arr3 = np.arange(10, 15)
print(arr3)

arr4 = np.array([i for i in range(10)])
print(arr4)

[1 2 3]
[0 1 2 3 4]
[10 11 12 13 14]
[0 1 2 3 4 5 6 7 8 9]


### Step 3. Reshape 1D to 2D Array

In [18]:
# reshape(n, m) -> original array's total element = n*m

temp_array = np.arange(1, 7)
print('1D array:', temp_array)

print()

arr5 = temp_array.reshape(3, 2)
print(arr5)

print()

arr5 = temp_array.reshape(2, 3)
print(arr5)

1D array: [1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]


### Step 4. Create a Linspace array

In [ ]:
# by default 50 generate
np.linspace(14, 16) 

# give limit
np.linspace(14, 18, 20)

array([14.        , 14.21052632, 14.42105263, 14.63157895, 14.84210526,
       15.05263158, 15.26315789, 15.47368421, 15.68421053, 15.89473684,
       16.10526316, 16.31578947, 16.52631579, 16.73684211, 16.94736842,
       17.15789474, 17.36842105, 17.57894737, 17.78947368, 18.        ])

### Step 5. Create a Random Numbered Array

In [ ]:
# row/column (generate between 0 to 1)
arr6 = np.random.rand(3,2)
print(arr6)

[[0.68303724 0.28233269]
 [0.04227778 0.3207988 ]
 [0.72800704 0.89276108]]


### Step 6. Create a Random Integer Array

In [ ]:
# start to last-1 
arr7 = np.random.randint(10,15)
print(arr7)

print("----------")

arr8 = np.random.randint(10,16, size=10)
print(arr8)

print("----------")

arr9 = np.random.randint(10,16, size=(4,4))
print(arr9)

13
[12 11 15 13 15 13 14 11 14 14]
----------
[[15 14 12 13]
 [13 11 14 11]
 [10 14 14 10]
 [15 14 14 10]]


### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [36]:
a7 = np.random.randint(5, 25, size=10)
print(a7)

[ 9 18  9  5  7 22 21 20  6 17]


In [38]:
print(a7.max())

22


In [39]:
a7.min()

np.int32(5)

In [ ]:
# return first max element's index
print(a7.argmax())  

5


In [ ]:
# return first min element's index
a7.argmin()

np.int64(3)

### Step 8. Indexing in 1D Array

In [ ]:
a8 = np.random.randint(5, 25, size=18)
print(a8)

# indexing means slicing
print(a8[5])

print(a8[2:6])

[13 21  5  5  9 24 19 10 18  8 22  6 17 23 24 10  7 14]
24
[ 5  5  9 24]


In [54]:
a8.dtype

dtype('int32')

### Step 9. Indexing in 2D Array

In [25]:
a9 = np.random.randint(1,20, size=(5,5))
# a9  # print with dtype
print(a9)  # output without dtype

[[13 12  7  3 10]
 [ 7  5 19 15 10]
 [17  6  1 11  6]
 [ 6 17  6 16 17]
 [11 12 15  4  6]]


In [26]:
print(a9[0])  # first row

[13 12  7  3 10]


In [ ]:
print(a9[0:2])  # noraml slicing

[[13 12  7  3 10]
 [ 7  5 19 15 10]]


In [33]:
# return 1st row and 2nd index's element
print(a9[1,2]) 

19


### Step 10. Conditional Selection

In [37]:
a10 = np.random.randint(1, 40, size=10)
print(a10)

[ 8  7 34 29 25 12  7  6  4 25]


In [41]:
# li = [i for i in a10 if i>25]
# print(li)

# Single condition
print(a10[a10 > 25])

# return Bool value
print(a10 > 25)

# Multi Condition
print(a10[(a10>25) | (a10<10)])

[34 29]
[False False  True  True False False False False False False]
[ 8  7 34 29  7  6  4]


### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [45]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [46]:
# without pipe
user_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")
user_data 

user_id|age|gender|occupation|zip_code
0                  1|24|M|technician|85711
1                       2|53|F|other|94043
2                      3|23|M|writer|32067
3                  4|24|M|technician|43537
4                       5|33|F|other|15213
..                                     ...
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

[943 rows x 1 columns]

In [47]:
# with pipe(it it alreay seperated by pipe in datasets)
user_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep='|')
user_data 

user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [48]:
# make user_id as index column
user_data = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep='|', index_col="user_id")
user_data 

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

In [49]:
# head -> starting from top
print(user_data.head(25))

         age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writ

### Step 5. See the last 10 entries

In [50]:
# head -> starting from bottom
print(user_data.tail(10))

         age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841


### Step 6. What is the number of observations in the dataset?

In [51]:
# Observation -> Count of Row/Col (Using shape)
print(user_data.shape)

user_data.shape[0] # only rows
user_data.shape[1] # only cols

(943, 4)


4

### Step 7. What is the number of columns in the dataset?

In [ ]:
user_data.shape[1]  # return the number of columns in the data
# user_data.shape[0]  # return the number of rows in the data

4

### Step 8. Print the name of all the columns.

In [52]:
user_data.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [53]:
user_data.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

In [54]:
print(user_data.dtypes)

age            int64
gender        object
occupation    object
zip_code      object
dtype: object


### Step 11. Print only the occupation column

In [ ]:
# user_data['occupation'] 

user_data.occupation  # (Both are equals)

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [58]:
# unique -> name of unique occupation
print(user_data.occupation.unique())

# nunique -> count of unique occupation
user_data.occupation.nunique()

['technician' 'other' 'writer' 'executive' 'administrator' 'student'
 'lawyer' 'educator' 'scientist' 'entertainment' 'programmer' 'librarian'
 'homemaker' 'artist' 'engineer' 'marketing' 'none' 'healthcare' 'retired'
 'salesman' 'doctor']


21

### Step 13. What is the most frequent occupation?

In [102]:
# user_data['occupation'].value_counts().head()

user_data['occupation'].value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

In [ ]:
# Describe -> summary of entire dataframe

# Describe -> numaric column's analysis
user_data.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

In [ ]:
# Describe -> include all for all columns
user_data.describe(include="all")

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [107]:
user_data['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [111]:
print(user_data['age'].mean())

34.05196182396607


### Step 18. What is the age with least occurrence?

In [112]:
user_data.age.value_counts().tail()

age
7     1
11    1
66    1
10    1
73    1
Name: count, dtype: int64

### You're not just learning, you're mastering it. Keep aiming higher! 🚀